server:
  port: 6100
  servlet:
    context-path: /iot
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://150.109.65.170:5432/demo
    username: postgres
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
